// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDseOkXNPC5hPQY-sqrl1-Y1fk5yGrFLiA',
    appId: '1:466141991536:android:b8abc601f5a0ac27d11ab5',
    messagingSenderId: '466141991536',
    projectId: 'flutterauth-cfe7f',
    storageBucket: 'flutterauth-cfe7f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBf0NJRqPgi3_qHoHLP5gL9OUVYkLxCV7A',
    appId: '1:466141991536:ios:8cb1ac8ca397a999d11ab5',
    messagingSenderId: '466141991536',
    projectId: 'flutterauth-cfe7f',
    storageBucket: 'flutterauth-cfe7f.firebasestorage.app',
    androidClientId: '466141991536-2dpv7lp0a9n8k4kbm11qfh9j0qg5krqi.apps.googleusercontent.com',
    iosClientId: '466141991536-h8cqmn2eafrfg3i2pqujmnq5o6finlg8.apps.googleusercontent.com',
    iosBundleId: 'com.flutterAuth.app',
  );

static const FirebaseOptions web = FirebaseOptions(
    apiKey: '466141991536-mbcsc9rqu5r8n6ih89770lcd4fpknu5i.apps.googleusercontent.com',
    appId: '1:466141991536:ios:8cb1ac8ca397a999d11ab5',
    messagingSenderId: '466141991536',
    projectId: 'flutterauth-cfe7f',
    storageBucket: 'flutterauth-cfe7f.firebasestorage.app',
    androidClientId: '466141991536-2dpv7lp0a9n8k4kbm11qfh9j0qg5krqi.apps.googleusercontent.com',
    iosClientId: '466141991536-h8cqmn2eafrfg3i2pqujmnq5o6finlg8.apps.googleusercontent.com',
    iosBundleId: 'com.flutterAuth.app',
  );

}